# Generated by Django 3.0.5 on 2020-07-30 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0002_profile_userearnings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userearnings',
            options={'verbose_name': 'User Earnings', 'verbose_name_plural': 'User Earnings'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_business',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_individual',
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('01', 'INIDIVDUAL'), ('02', 'BUSINESS')], default='01', max_length=10),
        ),
        migrations.CreateModel(
            name='UserTransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CR', 'CREDIT'), ('DR', 'DEBIT')], max_length=2)),
                ('amount', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
