# Generated by Django 3.0.5 on 2020-12-13 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acctmang', '0003_auto_20200730_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 13, 5, 20, 25, 132264, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
