# Generated by Django 3.0.5 on 2020-04-21 21:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('capital_city', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('information', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Covered Country',
                'verbose_name_plural': 'Covered Country Plural',
            },
        ),
    ]
