# Generated by Django 3.0.5 on 2020-04-21 22:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveredcountry',
            options={'verbose_name': 'Covered Country', 'verbose_name_plural': 'Covered Countries'},
        ),
        migrations.AlterField(
            model_name='coveredcountry',
            name='capital_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coveredcountry',
            name='currency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coveredcountry',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='coveredcountry',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coveredcountry',
            name='temperature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
