# Generated by Django 3.0.5 on 2020-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200421_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveredcountry',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='uploads/countries'),
        ),
    ]
