# Generated by Django 3.0.5 on 2020-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200422_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveredcountry',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='static/uploads/countries'),
        ),
    ]
