# Generated by Django 3.0.5 on 2020-04-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200422_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry', models.TextField()),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
                ('country_of_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='base.CoveredCountry')),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='base.CoveredCountry')),
            ],
            options={
                'verbose_name': 'Travel Information',
                'verbose_name_plural': 'Travel Information',
            },
        ),
    ]
