# Generated by Django 3.0.5 on 2020-04-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_travelinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInsurace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('insurance_type', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
                ('country_of_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_insurance_destination', to='base.CoveredCountry')),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_insurance_origin', to='base.CoveredCountry')),
            ],
            options={
                'verbose_name': 'Travel Insurance',
                'verbose_name_plural': 'Travel Insurance',
            },
        ),
        migrations.CreateModel(
            name='TravelAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry', models.TextField()),
                ('document', models.ImageField(upload_to='static/uploads/travels')),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
                ('country_of_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_assistance_destination', to='base.CoveredCountry')),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_assistance_origin', to='base.CoveredCountry')),
            ],
            options={
                'verbose_name': 'Travel Assistance',
                'verbose_name_plural': 'Travel Assistance',
            },
        ),
    ]
