# Generated by Django 3.0.5 on 2020-04-23 07:28

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_travelassistance_travelinsurace'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200)),
                ('deal_image', models.ImageField(upload_to='static/uploads/tours')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('information', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
