# Generated by Django 3.0.5 on 2020-08-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200722_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[('ONE WAY', 'ONE WAY'), ('RETURN TICKET', 'RETURN TICKET')], max_length=20)),
                ('ticket_class', models.CharField(choices=[('FIRST CLASS', 'FIRST CLASS'), ('BUSINESS', 'BUSINESS'), ('ECONOMY', 'ECONOMY')], max_length=20)),
                ('no_of_travellers', models.CharField(max_length=20)),
                ('airport_pickup', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
                ('hotel_reservation', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5)),
                ('duration_of_stay', models.CharField(max_length=20)),
                ('estimated_budget_value', models.CharField(max_length=20)),
                ('estimated_budget_currency', models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=3)),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
                ('country_of_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_budget_destination', to='base.CoveredCountry')),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_budget_origin', to='base.CoveredCountry')),
            ],
            options={
                'verbose_name': 'Travel Budget',
                'verbose_name_plural': 'Travel Budget',
            },
        ),
    ]
