# Generated by Django 3.0.5 on 2020-08-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_travelbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCustomTourRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('country_of_destination', models.CharField(max_length=100)),
                ('tour_category', models.CharField(choices=[('INDIVIDUAL', 'INDIVIDUAL'), ('COUPLE', 'COUPLE'), ('FAMILY', 'FAMILY'), ('CORPORATE', 'CORPORATE')], max_length=50)),
                ('message', models.TextField()),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
