# Generated by Django 3.0.5 on 2020-08-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_userscustomtourrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdeal',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tourdeal',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tourdeal',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('NGN', 'NGN')], max_length=3, null=True),
        ),
    ]
