# Generated by Django 3.0.5 on 2020-08-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200803_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDealInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('number_of_travellers', models.IntegerField()),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='base.TourDeal')),
            ],
        ),
    ]
