# Generated by Django 3.0.5 on 2020-08-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200803_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelassistance',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='useruploads'),
        ),
    ]
