# Generated by Django 3.0.5 on 2020-12-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200803_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=100)),
                ('request_info', models.TextField()),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
