# Generated by Django 3.0.5 on 2020-12-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_requestchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReferralRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliate_id', models.CharField(max_length=100)),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
