# Generated by Django 3.0.5 on 2020-12-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_customerreferralrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveredcountry',
            options={'ordering': ['country_name'], 'verbose_name': 'Covered Country', 'verbose_name_plural': 'Covered Countries'},
        ),
    ]
