# Generated by Django 3.0.5 on 2023-08-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20201220_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostArrivalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('approved_visa_type', models.CharField(choices=[('VISA ONE', 'VISA ONE'), ('VISA TWO', 'VISA TWO'), ('VISA THREE', 'VISA THREE'), ('VISA FOUR', 'VISA FOUR')], max_length=200)),
                ('document', models.ImageField(blank=True, null=True, upload_to='static/uploads/post-arrival-services')),
                ('arrival_date', models.DateField()),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
                ('accomodation_type', models.CharField(choices=[('ACCOMODATION ONE', 'ACCOMODATION ONE'), ('ACCOMODATION TWO', 'ACCOMODATION TWO'), ('ACCOMODATION THREE', 'ACCOMODATION THREE'), ('ACCOMODATION FOUR', 'ACCOMODATION FOUR')], max_length=200)),
                ('final_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_arrival_services_destination', to='base.CoveredCountry')),
            ],
            options={
                'verbose_name': 'Post Arrival Service',
                'verbose_name_plural': 'Post Arrival Services',
            },
        ),
    ]
