# Generated by Django 3.0.5 on 2023-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_postarrivalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry', models.TextField()),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Service',
                'verbose_name_plural': 'Customer Services',
            },
        ),
    ]
