# Generated by Django 3.0.5 on 2023-08-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20230802_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinsurance',
            name='hello',
        ),
    ]
