# Generated by Django 3.0.5 on 2023-08-23 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_newslettersubscriber_datetime_of_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinsurance',
            name='date_of_arrival',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelinsurance',
            name='date_of_departure',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
