# Generated by Django 3.0.5 on 2023-10-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20231002_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='meeting_type',
            field=models.CharField(choices=[('PHYSICAL', 'PHYSICAL'), ('VIRTUAL', 'VIRTUAL')], default='VIRTUAL', max_length=100),
            preserve_default=False,
        ),
    ]
