# Generated by Django 3.0.5 on 2023-10-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_relationship_visaassistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_institution', models.CharField(max_length=200)),
                ('educational_level', models.CharField(choices=[('PRIMARY', 'PRIMARY'), ('SECONDARY', 'SECONDARY'), ('TERTIARY', 'TERTIARY')], max_length=200)),
                ('date_attended', models.DateField()),
                ('date_graduated', models.DateField()),
                ('institution_address', models.CharField(max_length=200)),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.VisaAssistance')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
    ]
