# Generated by Django 3.0.5 on 2023-10-08 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20231009_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='applicant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='base.VisaAssistance'),
        ),
    ]
