# Generated by Django 3.0.5 on 2023-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_applicationinformation_otherinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherinformation',
            name='extra_curicular_activity',
        ),
        migrations.AddField(
            model_name='otherinformation',
            name='extra_curicular_activities',
            field=models.TextField(null=True),
        ),
    ]
