# Generated by Django 3.0.5 on 2023-10-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_consultation_meeting_type'),
        ('base', '0032_auto_20231009_1500'),
    ]

    operations = [
    ]
