# Generated by Django 3.0.5 on 2023-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20231023_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdeal',
            name='number_of_travellers',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
