# Generated by Django 3.0.5 on 2023-10-28 16:18

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_tourdeal_number_of_travellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article', ckeditor.fields.RichTextField(blank=True)),
                ('banner_image', models.ImageField(upload_to='posts/')),
                ('preview_image', models.ImageField(upload_to='posts/')),
                ('published', models.BooleanField(default=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('datetime_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tourdeal',
            name='datetime_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
