# Generated by Django 3.0.5 on 2023-10-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20231028_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='published',
            new_name='publish',
        ),
    ]
